name: pms_mobile
description: PMS Mobile.
publish_to: "none"

version: 1.1.1+22

environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  bot_toast: ^4.1.3
  get: ^4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  easy_refresh: ^3.3.2+4
  mobile_scanner: ^3.5.5
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  logger: ^2.0.2+1
  open_filex: ^4.3.4
  vibration: ^1.8.4
  flutter_local_notifications: ^16.2.0
  file_picker: ^6.1.1
  pdfx:
    git:
      url: https://github.com/ScerIO/packages.flutter
      ref: 8b105a7dfc6b90220c1d79fcb805fb764cab00c5
      path: packages/pdfx
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
  macos:
    generate: false
    image_path: "assets/images/launcher_icon.png"

# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#f6ff6f"
  image: "assets/images/splash.png"
  branding: assets/images/splash_branding.png
  android_12:
    image: "assets/images/splash.png"
    branding: assets/images/splash_branding.png
  web: false
