part of '../index.dart';

class CustomCheckboxListTile extends CheckboxListTile {
  const CustomCheckboxListTile({
    super.key,
    required super.value,
    required super.onChanged,
    super.mouseCursor,
    super.activeColor,
    super.fillColor,
    super.checkColor,
    super.hoverColor,
    super.overlayColor,
    super.splashRadius,
    super.materialTapTargetSize,
    super.visualDensity,
    super.focusNode,
    super.autofocus,
    super.shape,
    super.side,
    super.isError,
    super.enabled,
    super.tileColor,
    super.title,
    super.subtitle,
    super.isThreeLine,
    super.dense,
    super.secondary,
    super.selected,
    super.controlAffinity,
    super.contentPadding,
    super.tristate,
    super.checkboxShape,
    super.selectedTileColor,
    super.onFocusChange,
    super.enableFeedback,
    super.checkboxSemanticLabel,
  });
}
